// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASnIXNCE18aMxt3p498hEqE_i1U0MgnXw',
    appId: '1:985253585457:web:a3bd0d6668c1c87c2e6b10',
    messagingSenderId: '985253585457',
    projectId: 'flutterapplogin-c2bed',
    authDomain: 'flutterapplogin-c2bed.firebaseapp.com',
    storageBucket: 'flutterapplogin-c2bed.appspot.com',
    measurementId: 'G-FWWS1Y9JMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKhHwgGIU677dLD5T6KCpGcz72eW6pgxI',
    appId: '1:985253585457:android:b86dd9bc994e17822e6b10',
    messagingSenderId: '985253585457',
    projectId: 'flutterapplogin-c2bed',
    storageBucket: 'flutterapplogin-c2bed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB57qkKdFMh7iocenf_FSVhlCIAmKOTvH4',
    appId: '1:985253585457:ios:54add6a3f839859a2e6b10',
    messagingSenderId: '985253585457',
    projectId: 'flutterapplogin-c2bed',
    storageBucket: 'flutterapplogin-c2bed.appspot.com',
    iosClientId: '985253585457-aat7ffn6r7jdojnvb5vlon49feea7og0.apps.googleusercontent.com',
    iosBundleId: 'com.example.connexion',
  );
}
